version: '3.2'
services:

 app:
   build:
     context: ./
     dockerfile: Dockerfile
   working_dir: /var/www
   volumes:
     - ./:/var/www
   environment:
     - "DB_PORT=3306"
     - "DB_HOST=database"
     - "DB_DATABASE=homestead"
     - "DB_USERNAME=homestead"
     - "DB_PASSWORD=secret"
   user: $UID

 web:
   image: nginx:stable
   volumes:
     - type: bind
       source: ./config-server/nginx/vhost.conf
       target: /etc/nginx/conf.d/default.conf
       read_only: true
   ports:
     - 8080:80

 database:
   image: mysql:5.7
   volumes:
     - dbdata:/var/lib/mysql
   environment:
     - "MYSQL_DATABASE=homestead"
     - "MYSQL_USER=homestead"
     - "MYSQL_PASSWORD=secret"
     - "MYSQL_ROOT_PASSWORD=secret"
   ports:
       - "33061:3306"

volumes:
 dbdata: